// <auto-generated />
using System;
using AWESOME.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AWESOME.Migrations
{
    [DbContext(typeof(AwesomeDbContext))]
    [Migration("20260611181341_ObservacionesOperativas")]
    partial class ObservacionesOperativas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AWESOME.Models.Entidades.AperturaContenedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anotaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Anticipado")
                        .HasColumnType("bit");

                    b.Property<string>("ArchivoExcel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bodega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bultos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CargaPaletizada")
                        .HasColumnType("bit");

                    b.Property<bool>("CargaSuelta")
                        .HasColumnType("bit");

                    b.Property<string>("Contenedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Embalaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Entarimado")
                        .HasColumnType("bit");

                    b.Property<bool>("Etiquetado")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtraccionMuestras")
                        .HasColumnType("bit");

                    b.Property<string>("Factura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAduana")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDespacho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalDescarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioDescarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInventario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRepVacio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalidaVacio")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraAduana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraApertura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraDespacho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraFinalDescarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraInicioDescarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraInventario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraRepVacio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraSalidaVacio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Importador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InformacionCorreo")
                        .HasColumnType("bit");

                    b.Property<string>("Inventario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManejoEspecial")
                        .HasColumnType("bit");

                    b.Property<string>("Marchamo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MarchamosAdicionales")
                        .HasColumnType("bit");

                    b.Property<string>("Mercaderia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroViaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Peonaje")
                        .HasColumnType("bit");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reexportacion")
                        .HasColumnType("bit");

                    b.Property<bool>("RollosPlasticos")
                        .HasColumnType("bit");

                    b.Property<bool>("SeparacionMercaderia")
                        .HasColumnType("bit");

                    b.Property<bool>("ServicioMontacargas")
                        .HasColumnType("bit");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tarimas")
                        .HasColumnType("bit");

                    b.Property<string>("Transportista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsoCamaraRefrigerada")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AperturasContenedores");
                });

            modelBuilder.Entity("AWESOME.Models.Entidades.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesSistema");
                });
#pragma warning restore 612, 618
        }
    }
}
